services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make php
  - make test-php

after_success:
  - test $TRAVIS_BRANCH = "master" && make deploy
