sudo: required

language: ruby

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make build
  - make test

after_success:
  - test $TRAVIS_BRANCH = "master" && make deploy
